fun main()
{
    println("Student Details")
    var a1=readLine()
    var a2=readLine()
    var a3=readLine()
    var a4=readLine()
    var a5=readLine()
    var a6=readLine()
    var a7=readln()
    var a8=readLine()
    println("Student Enrollment No:" +a1)
    println("Student Name:" +a2)
    println("Student Branch:" +a3)
    println("Student Class:" +a4)
    println("Student Batch:" +a5)
    println("Student College Name:" +a6)
    println("Student University Name:" +a7)
    println("Student Age:" +a8)
}